---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: kueue-demo
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
        - pods
      flavors:
        - name: default-flavor
          resources:
            - name: cpu
              nominalQuota: 1000m
            - name: memory
              nominalQuota: 2048Mi
            - name: pods
              nominalQuota: 4
