apiVersion: batch/v1
kind: Job
metadata:
  generateName: demo-
  namespace: demo-jobs
  labels:
    kueue.x-k8s.io/queue-name: demo-jobs
spec:
  parallelism: 4
  completions: 10
  suspend: true
  template:
    spec:
      containers:
        - name: sleep-30s
          image: busybox
          command:
            - sleep
          args:
            - 30s
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      restartPolicy: Never
