name: lab5-gcp-dev1
run-name: lab5-gcp-dev1

on: pull_request

env:
  google_project: lab5-gcp-dev1
  workload_identity_provider: projects/320561780581/locations/global/workloadIdentityPools/github/providers/google-infra

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Code Checkout
        uses: actions/checkout@v4
      - id: auth
        name: Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.google_project }}
          workload_identity_provider: ${{ env.workload_identity_provider }}
      - id: cache
        name: Terraform Cache
        uses: actions/cache@v4
        with:
          path: terraform/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}
      - id: terraform-plan
        name: Terraform Plan
        run: |-
          google_project=${{ env.google_project }} make settings terraform-plan

  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ env.GCP_PROJECT }}
    needs: terraform-plan
    steps:
      - id: checkout
        name: Code Checkout
        uses: actions/checkout@v4
      - id: auth
        name: Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.google_project }}
          workload_identity_provider: ${{ env.workload_identity_provider }}
      - id: cache
        name: Terraform Cache
        uses: actions/cache@v4
        with:
          path: terraform/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}
      - id: terraform-apply
        name: Terraform Apply
        run: |-
          google_project=${{ env.google_project }} make settings terraform-plan
